name: Aggiorna Prezzi Carburante

on:
  schedule:
    - cron: '0 */6 * * *' # Esegue lo script ogni 6 ore
  workflow_dispatch: # Permette di avviarlo anche a mano con un pulsante

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installa le dipendenze
        run: npm install

      - name: Esegui lo script di estrazione
        run: node index.js

     - name: Salva e pubblica il nuovo JSON
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add -f prezzi-italia.json
          git commit -m "Aggiornamento prezzi automatico" || exit 0
          git push
